Repository citrushack/cutiehack2023, pull requests merged in 2023-10, with the labels that each got.

#1 coming soon
  .github/workflows/pull-request.yaml
  README.md
  cypress.config.js
  package.json
  public/logo.svg
  public/shine.svg
  public/submarine.svg
  src/app/admin/messenger/page.js
  src/app/layout.js
  src/app/page.js
  src/components/Navigation.jsx
  src/components/ProtectedPage.jsx
  src/components/comingSoon/ComingSoon.jsx
  src/components/comingSoon/Countdown.jsx
  src/data/Release.js
  tailwind.config.js
Labels: read to reivew

#26 Add Seconds
  src/components/comingSoon/Countdown.jsx
Labels: ready to merge

#28 Menthy/comingsoon
  public/svg/bubble.svg
  public/svg/stingray.svg
  public/svg/submarine.svg
  src/components/static/Link.jsx
  src/components/static/prelive/landing/Link.jsx
  src/components/static/upcoming/Upcoming.jsx
  tailwind.config.js
Labels: coming soon

#37 add icon
  src/app/favicon.ico
Labels: read to reivew

#36 Menthy/fixes
  src/components/static/Countdown.jsx
Labels: read to reivew

#38 restyle form
  src/components/dynamic/forms/Form.jsx
Labels: read to reivew

#39 style inputs
  src/components/dynamic/Checkbox.jsx
  src/components/dynamic/Input.jsx
  src/components/dynamic/Radio.jsx
  src/components/dynamic/Select.jsx
  src/components/dynamic/forms/Admin.jsx
  src/components/dynamic/forms/Committee.jsx
  src/components/dynamic/forms/Feedback.jsx
  src/components/dynamic/forms/Form.jsx
  src/components/dynamic/forms/Participant.jsx
  src/components/dynamic/forms/Textarea.jsx
  src/components/dynamic/forms/Upload.jsx
  src/data/dynamic/Button.js
  src/data/dynamic/forms/Availability.js
  src/data/dynamic/forms/Mentors.js
  src/data/dynamic/forms/Participant.js
  src/data/dynamic/forms/Volunteers.js
Labels: read to reivew

#51 dashbaord
  cypress/e2e/admins/admins/Filter.cy.js
  cypress/e2e/admins/admins/Select.cy.js
  cypress/e2e/admins/committees/Filter.cy.js
  cypress/e2e/admins/committees/Select.cy.js
  cypress/e2e/admins/judges/Filter.cy.js
  cypress/e2e/admins/judges/Select.cy.js
  cypress/e2e/admins/mentors/Filter.cy.js
  cypress/e2e/admins/mentors/Select.cy.js
  cypress/e2e/admins/participants/Filter.cy.js
  cypress/e2e/admins/participants/Select.cy.js
  cypress/e2e/admins/teams/Filter.cy.js
  cypress/e2e/admins/teams/Select.cy.js
  cypress/e2e/admins/volunteers/Filter.cy.js
  cypress/e2e/admins/volunteers/Select.cy.js
  src/components/dynamic/admin/Filters.jsx
  src/components/dynamic/admin/Input.jsx
  src/components/dynamic/admin/Table.jsx
  src/components/dynamic/admin/Tag.jsx
  src/data/dynamic/Tags.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Volunteers.js
  tailwind.config.js
Labels: read to reivew

#57 fix loading and error
  src/app/layout.js
  src/app/not-found.js
  src/components/dynamic/Error.jsx
  src/components/dynamic/Loading.jsx
Labels: read to reivew

#56 checkin color
  src/components/dynamic/user/CheckIn.jsx
Labels: read to reivew

#46 Added Button
  src/components/static/prelive/Apply.jsx
Labels: read to reivew, prelive

#58 About.jsx
  src/components/static/prelive/about/About.jsx
Labels: read to reivew

#59 Menthy/merge
  src/app/api/participant/route.js
  src/app/api/teams/route.js
  src/components/dynamic/Navigation.jsx
  src/components/dynamic/admin/Title.jsx
  src/components/dynamic/admin/services/statistics/Tab.jsx
  src/components/dynamic/forms/Form.jsx
  src/components/dynamic/forms/Judge.jsx
  src/components/dynamic/forms/Mentor.jsx
  src/components/dynamic/forms/Participant.jsx
  src/components/dynamic/forms/Volunteer.jsx
  src/components/dynamic/user/Dashboard.jsx
  src/components/dynamic/user/User.jsx
  src/data/dynamic/Navigation.js
  src/data/dynamic/forms/Admins.js
  src/data/dynamic/forms/Committees.js
  src/data/dynamic/forms/Judge.js
  src/data/dynamic/forms/Mentors.js
  src/data/dynamic/forms/Participant.js
  src/data/dynamic/forms/Volunteers.js
Labels: ready to review

#54 fix profile header
  src/components/dynamic/user/Header.jsx
  src/components/dynamic/user/User.jsx
Labels: ready to review

#61 added marging
  src/components/static/upcoming/Upcoming.jsx
Labels: ready to review

#53 Menthy/title
  src/components/dynamic/admin/Title.jsx
  src/components/dynamic/admin/services/statistics/Tab.jsx
  src/components/dynamic/user/CheckIn.jsx
  src/components/dynamic/user/Dashboard.jsx
Labels: ready to review

#65 Error Finalized
  src/app/error.js
  src/app/not-found.js
  src/components/dynamic/Error.jsx
Labels: ready to merge
