Repository citrushack/cutiehack2023, pull requests merged in 2023-11, with the labels that each got.

#60 added accordion component
  src/components/static/prelive/faq/FAQ.jsx
  src/components/static/prelive/faq/FAQ_styles.css
  src/data/static/FAQ.js
Labels: ready to review, prelive

#86 map through committee
  package-lock.json
  package.json
  src/components/static/prelive/team/Committees.jsx
  src/data/static/Committees.js
Labels: prelive

#94 changed hackathon name
  src/components/dynamic/admin/services/Messenger.jsx
  src/data/Config.js
Labels: ready to review

#96 changed icons to white
  src/data/dynamic/Tags.js
  src/data/dynamic/admin/Icons.js
Labels: ready to review

#101 changed to white
  src/components/dynamic/admin/services/calendar/CustomHeader.jsx
  src/components/dynamic/admin/services/calendar/Events.jsx
Labels: ready to review

#111 changed header colors
  src/components/dynamic/admin/dashboards/Modal.jsx
Labels: ready to review

#123 fix faq focus
  src/components/static/prelive/faq/Item.jsx
Labels: ready to review

#121 add footer
  public/svg/footer.svg
  src/components/static/Footer.jsx
  src/components/static/prelive/Prelive.jsx
  src/data/static/Social.js
Labels: ready to review
